// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsesGxa6qRVXZR3qgo6OuyUGVheoyKfME',
    appId: '1:1043432749188:web:7cbd5cc3e76ada3ec76ad1',
    messagingSenderId: '1043432749188',
    projectId: 'chitchat-91ac5',
    authDomain: 'chitchat-91ac5.firebaseapp.com',
    storageBucket: 'chitchat-91ac5.appspot.com',
    measurementId: 'G-4D4Z2J6SMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEuiZaMHZO46kEsJJRUo37v4ke0kEaA1Y',
    appId: '1:1043432749188:android:907275674421ad37c76ad1',
    messagingSenderId: '1043432749188',
    projectId: 'chitchat-91ac5',
    storageBucket: 'chitchat-91ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiALNkF6tJK4vpV7l9tSImY0N71HYV0Hc',
    appId: '1:1043432749188:ios:08debaf08ae589afc76ad1',
    messagingSenderId: '1043432749188',
    projectId: 'chitchat-91ac5',
    storageBucket: 'chitchat-91ac5.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiALNkF6tJK4vpV7l9tSImY0N71HYV0Hc',
    appId: '1:1043432749188:ios:08debaf08ae589afc76ad1',
    messagingSenderId: '1043432749188',
    projectId: 'chitchat-91ac5',
    storageBucket: 'chitchat-91ac5.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsesGxa6qRVXZR3qgo6OuyUGVheoyKfME',
    appId: '1:1043432749188:web:8126ddb013c8e970c76ad1',
    messagingSenderId: '1043432749188',
    projectId: 'chitchat-91ac5',
    authDomain: 'chitchat-91ac5.firebaseapp.com',
    storageBucket: 'chitchat-91ac5.appspot.com',
    measurementId: 'G-HB3QXJFEBV',
  );
}
